import { PhotoResource } from "../../app/core/interfaces/resources/photo-resource.interface"

export const photoResourceCollection: PhotoResource[] = [
  {
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria1.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria1s.jpg',
    alt: 'Description for Image 1',
    title: 'Mexico',
    code: 'MX',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria2.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria2s.jpg',
    alt: 'Description for Image 2',
    title: 'Ukraine',
    code: 'UA',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria3.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria3s.jpg',
    alt: 'Description for Image 3',
    title: 'Netherlands',
    code: 'NL',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria4.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria4s.jpg',
    alt: 'Description for Image 4',
    title: 'United States',
    code: 'US',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria5.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria5s.jpg',
    alt: 'Description for Image 5',
    title: 'Spain',
    code: 'ES',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria6.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria6s.jpg',
    alt: 'Description for Image 6',
    title: 'India',
    code: 'IN',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria7.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria7s.jpg',
    alt: 'Description for Image 7',
    title: 'Turkey',
    code: 'TR',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria8.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria8s.jpg',
    alt: 'Description for Image 8',
    title: 'Canada',
    code: 'CA',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria9.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria9s.jpg',
    alt: 'Description for Image 9',
    title: 'New Zealand',
    code: 'NZ',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria10.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria10s.jpg',
    alt: 'Description for Image 10',
    title: 'United Kingdom',
    code: 'UK',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria11.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria11s.jpg',
    alt: 'Description for Image 11',
    title: 'Iran',
    code: 'IR',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria12.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria12s.jpg',
    alt: 'Description for Image 12',
    title: 'Australia',
    code: 'AU',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria13.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria13s.jpg',
    alt: 'Description for Image 13',
    title: 'Ireland',
    code: 'IE',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14s.jpg',
    alt: 'Description for Image 14',
    title: 'Norway',
    code: 'NO',
},
{
    itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15.jpg',
    thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15s.jpg',
    alt: 'Description for Image 15',
    title: 'Serbia',
    code: 'RS',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15s.jpg',
  alt: 'Description for Image 15',
  title: 'Finland',
  code  : 'FI',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15s.jpg',
  alt: 'Description for Image 15',
  title: 'Brazil',
  code  : 'BR',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria15s.jpg',
  alt: 'Description for Image 15',
  title: 'Switzerland',
  code  : 'CH',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14s.jpg',
  alt: 'Description for Image 14',
  title: 'Germany',
  code  : 'DE',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria14s.jpg',
  alt: 'Description for Image 14',
  title: 'Denmark',
  code  : 'DK',
},
{
  itemImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria4.jpg',
  thumbnailImageSrc: 'https://primefaces.org/cdn/primeng/images/galleria/galleria4s.jpg',
  alt: 'Description for Image 4',
  title: 'France',
  code  : 'FR',
},
]
